### ISSUE TITLE
Upgrade to openssh v0.9.0 with native-mux feature?

### ISSUE THREAD

**Issue by NobodyXu** [jaywonchung/pegasus#1]
[openssh v0.9.0-rc1] is released with a new feature `native-mux`.

It provides new functions like [`Session::connect_mux`] and [`SessionBuilder::connect_mux`] which communicates with the ssh multiplex master directly, through the control socket, instead of spawning a new process to communicate with it.

The advantage of this is more robust error reporting, better performance and less memory usage.

The old implementation (`process-mux`) checks the exit status of `ssh` for indication of error, then parse the output of it and the output of the ssh multiplex master to return an error.

This method is obviously not so robust as `native-mux`, which directly communicates with ssh multiplex master through its [multiplex protocol].

The better performance and less memory usage part is mostly because we avoid creating a new process for every command you spawned on remote, every [`Session::check`] and every [`Session::request_port_forwarding`].

The new release also add new function [`Session::request_port_forwarding`], which supports local/remote forwarding of tcp and unix socket stream.

There are also other changes to API:
 - A new type [`Stdio`] is used for setting stdin/stdout/stderr.
 - `ChildStd*` types are now alias for `tokio_pipe::{PipeRead, PipeWrite}`.
 - [`Command::spawn`] and [`Command::status`] now confirms to `std::process::Command` and `tokio::process::Command`, in which stdin, stdout and stderr are inherit by default.
 - [`Command::spawn`] is now an `async` method.
 - [`RemoteChild::wait`] now takes `self` by value.
 - [`Error`] is now marked `#[non_exhaustive]` and new variants is added.

I know this is a huge release and upgrading it is going to be quite difficult, but I sincerely want you to try it out, as the new implementation requires feedback.

[multiplex protocol]: https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.mux
[openssh v0.9.0-rc1]: https://docs.rs/openssh/0.9.0-rc.1/openssh/index.html
[`Stdio`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/struct.Stdio.html
[`Error`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/enum.Error.html
[`Command::spawn`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/struct.Command.html#method.spawn
[`Command::status`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/struct.Command.html#method.status
[`Session::connect_mux`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/struct.Session.html#method.connect_mux
[`SessionBuilder::connect_mux`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/struct.SessionBuilder.html#method.connect_mux
[`Session::request_port_forwarding`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/struct.Session.html#method.request_port_forward
[`RemoteChild::wait`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/struct.RemoteChild.html#method.wait
[`Session::check`]: https://docs.rs/openssh/0.9.0-rc.1/openssh/struct.Session.html#method.check

**Comment by jaywonchung** [comment]
Thanks for the suggestion! Not needing to spawn new `ssh` processes seems very attractive. I definitely anticipate performance and memory enhancements improving usability, and robust error reporting is good to have.

One small thing on my end is that I'm a grad student who can't really allocate a lot of time for development. So I need to spend time when urgent need arises and in general be efficient in using time. To that end, I think I'll do it one day if nobody does it before me, but not until 1) 0.9.0 becomes the latest stable version (so that things don't break when I'm running experiments and I don't have to invest more time adapting things when the stable version is released) and 2) I actually feel the need for better performance and/or memory (for error reporting, I usually run experiments via a LAN connecting a cluster of nodes so connection is usually stable, and the source of application error is usually evident from stdout + stderr in my case).

Anyway thanks! I'll definitely keep this in mind as a good pathway to take when Pegasus lacks performance.

**Comment by NobodyXu** [comment]
That is totally understandable!

I am also a student in my fourth year in the university, so I understand how busy the school can be.

**Comment by jaywonchung** [comment]
Thanks for understanding!

Actually, I'd like to keep this open so that I don't forget and keep it as a TODO. I'll be adding a few potential TODOs as issues, too.

**Comment by NobodyXu** [comment]
[openssh v0.9.0-rc.3](https://docs.rs/openssh/0.9.0-rc.3/openssh/index.html) has just released!

Here's the [changelog](https://docs.rs/openssh/0.9.0-rc.3/openssh/changelog/index.html).

**Comment by NobodyXu** [comment]
@jaywonchung 0.9.0 has finally released!

**Comment by jaywonchung** [comment]
Nice! Actually the timing is pretty good. I'm facing a paper deadline on April 20th, and after that, I'm going to resolve the issues posted on Pegasus. Thanks for letting me know!

**Comment by NobodyXu** [comment]
Pinging this issue

**Comment by jaywonchung** [comment]
Thanks for the reminder, @NobodyXu. However please note that I do not owe you the resolution of this issue. I resolve this if and when I see fit.

**Comment by NobodyXu** [comment]
> Thanks for the reminder, @NobodyXu. However please note that I do not owe you the resolution of this issue. I resolve this if and when I see fit.

I am sorry, I don't meant to sound authoritative.
I am really looking forward to see use of openssh in real world, if you are busy, then maybe I can help submit a PR.

**Comment by jaywonchung** [comment]
All good 👍 I (sadly) am not yet free from stuff to do, so if I am to work on this, it'll be some time during May. Always appreciate your help and interest!
